apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      name: http
    - port: 443
      name: ssl
  type: LoadBalancer
